### PR TITLE
For consistency align close button to the left in `ha-dialog`

### PR DESCRIPTION
**Pull request by jpbede**
## Proposed change
For consistency reasons this PR aligns the close button to the left for dialogs that use `createCloseHeading` of `ha-dialorg`.

| image | image |
|:-:|:-:|

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by MindFreeze — APPROVED** [review]
It would be best if we just used `ha-dialog-header` everywhere but this is a step in the right direction at least. Thanks

**Comment by jpbede** [comment]
I can check if I can migrate this to `ha-dialog-header`

**Comment by MindFreeze** [comment]
> I can check if I can migrate this to `ha-dialog-header`

Sure, have a go. My 5 min attempt was unsuccessful

**Comment by MindFreeze** [comment]
Also I am not 100% sure `ha-dialog-header` is the canonical way since I didn't do a deep analysis but it is used in the `more-info` dialog and supports an overflow menu

**Pull request merged**
