### PR TITLE
Add zoom & pan to charts

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Updates to the graph reset the chart so I had to stop updates while zoomed in. Shouldn't be an issue as the user is focusing on the data that is already there.

On mobile zoom & pan is done with touch.

On desktop
- Pan by dragging with the mouse
- Zoom:
    - ctrl + select a region of the chart to zoom in on
    - ctrl + scroll; an overlay is displayed on scroll like in embedded google maps

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
> 🎉 @MindFreeze We would need to add a reset zoom button somewhere

Indeed. I added double click to reset zoom for now but we need something more obvious for desktop. On mobile you can use your fingers

**Comment by MindFreeze** [comment]
We can add buttons later if we want but this is already very usable so we can merge it

**Comment by boern99** [comment]
Very nice! One thing i noticed: If you try to zoom out on a chart using binary or text sensors bar chart: the chart gets hidden and does not come back. Behavior is on desktop and my mobile.

**Comment by MindFreeze** [comment]
> Also `ctrl+select` triggers the context menu for me... not an ideal UX

Now I remember that's why I used `shift` in the beginning

**Comment by MindFreeze** [comment]
Looks like Google maps use the command button on Mac. Will change to that. They've made it work with `ctrl` as well but the hint says "⌘ + scroll"

**Comment by boern99** [comment]
Maybe it would in a later step also be possible to sync time periods across multiple charts: If for example timeline charts and graph charts is loaded at the same time:  Looks like the API could make this possible? chart.pan(delta, scales?, mode = 'none'): void (https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/developers.html#imperative-zoom-pan-api) 
On that base it perhaps would also be possible to recognize zoom out tries, even the chartjs-plugin has fully zoomed out, react on that and load a longer period of time?

**Comment by MindFreeze** [comment]
Zooming out for more data is tricky because then you can't easily return to the initial state. We'd have to pollute the UI with a reset button. Panning to the left to load older data would be easier though

**Comment by MindFreeze** [comment]
The text sensor chart will be fixed separately #23270

**Review by bramkragten — APPROVED** [review]

**Comment by Nasimovy** [comment]
i found a small bug

https://github.com/home-assistant/frontend/issues/23463

**Pull request merged**
