### PR TITLE
cover: Disable stop button when not opening/closing

### LINKED ISSUE #17945: Cover Button States
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### The problem

Cover button states are not dependent on `CoverOperation`

### ■ button state
■ button is always enabled (when `stop_action` is set) regardless of the cover state and operation (even when `COVER_OPERATION_IDLE`)

Cover Open
image 
Cover Closed
image 

■ button is expected to be
- **disabled** when `COVER_OPERATION_IDLE`
- **enabled** otherwise (`COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

### Stop direction change
The cover stop direction should be configurable.  
After stopping, covers may 
- ↓ ■ ↓ ■ ↓ ■ ↓ / continue in the same direction , or 
- ↓ ■ ↑ ■ ↓ ■ ↑ / continue in the opposite direction

### Instant operations 

The current behaviour has the opposite direction enabled when the cover is opening or closing.

↑ button is enabled during `COVER_OPERATION_CLOSING`
image 

↓ button is enabled during `COVER_OPERATION_OPENING`
image 

Not all covers can instantly switch direction from opening to closing.  A window blind may be able to go from opening to closing without stopping, but a garage door motors may first needs to stop before operating in the opposite direction.

↑ and ↓ buttons should be configurable to enable/disable instant operations.

↑ and ↓ buttons are expected to be
- **enabled** when `COVER_OPERATION_IDLE`
- **disabled** otherwise (when `CoverOperation` is either `COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

### Describe the behavior you expected

■ button is expected to be
- **disabled** when `COVER_OPERATION_IDLE`
- **enabled** otherwise (`COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

↑ and ↓ buttons are expected to be
- **enabled** when `COVER_OPERATION_IDLE`
- **disabled** otherwise (when `CoverOperation` is either `COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

### Steps to reproduce the issue

View cover while opening/closing.

### What version of Home Assistant Core has the issue?

2023.9.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

Reported [the issue](https://github.com/esphome/issues/issues/4788) to ESP Home, because I ran into the issue with the following yaml config, however it seems to be HA related.  

<details>
<summary>Click to expand</summary>

```yaml
binary_sensor:
  - platform: gpio
    pin: 
      number: ${open_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    id: cover_open
    internal: true
    name: "Cover Open"
    filters:
      delayed_on_off: 50ms
    on_state:
      lambda: |-
        if (id(cover_open).state && !id(cover_closed).state) {
          id(garage_door).position = cover::COVER_OPEN;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Open");
        } else if (!id(cover_open).state && !id(cover_closed).state) {
          if (id(garage_door).position == cover::COVER_OPEN) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_CLOSING;
            id(garage_door).publish_state();
            id(status).publish_state("Closing");
          } else if (id(garage_door).position == cover::COVER_CLOSED) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_OPENING;
            id(garage_door).publish_state();
            id(status).publish_state("Opening");
          }
        } else if (!id(cover_open).state && id(cover_closed).state) {
          id(garage_door).position = cover::COVER_CLOSED;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Closed");
        }

  - platform: gpio
    pin: 
      number: ${closed_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    id: cover_closed
    internal: true
    name: "Cover Closed"
    filters:
      delayed_on_off: 50ms
    on_state:
      lambda: |-
        if (id(cover_open).state && !id(cover_closed).state) {
          id(garage_door).position = cover::COVER_OPEN;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Open");
        } else if (!id(cover_open).state && !id(cover_closed).state) {
          if (id(garage_door).position == cover::COVER_OPEN) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_CLOSING;
            id(garage_door).publish_state();
            id(status).publish_state("Closing");
          } else if (id(garage_door).position == cover::COVER_CLOSED) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_OPENING;
            id(garage_door).publish_state();
            id(status).publish_state("Opening");
          }
        } else if (!id(cover_open).state && id(cover_closed).state) {
          id(garage_door).position = cover::COVER_CLOSED;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Closed");
        }

output:
  - platform: gpio
    pin: 
      number: ${relay_1_pin}
      inverted: false
    id: relay_1

button:
  - platform: output
    output: relay_1
    id: button_1
    disabled_by_default: true
    duration: 500ms
    name: "Button 1"
    icon: "mdi:gesture-tap-button"

cover:
  - platform: template
    name: "Garage Door"
    device_class: garage
    id: garage_door
    open_action:
      - button.press: button_1
    close_action:
      - button.press: button_1
    stop_action:
      - button.press: button_1
    optimistic: false

text_sensor:
  - platform: template
    icon: mdi:information-outline
    id: status
    name: "Status"
    disabled_by_default: true


</details>


### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gaaf**
## Proposed change

Disable the stop button when the cover is not moving.

Fixes/implements the below quoted part of issue: #17945:

> Cover button states are not dependent on `CoverOperation`
> ## `COVER_OPERATION_IDLE`
> ### ■ button state
> 
> ■ button is always enabled (when `stop_action` is set) regardless of the cover state and operation (even when `COVER_OPERATION_IDLE`)
> 
> Cover Open
image
Cover Closed
image
> 
> ■ button is expected to be
> 
>    * **disabled** when `COVER_OPERATION_IDLE`
> 
>    * **enabled** otherwise (`COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)
> 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #17945
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
Some cover doesn't have closing and opening state (zwave, overkiz) but can be stopped. We don't have these information in supported features so we can not disable the stop button.

**Comment by gaaf** [comment]
That's unfortunate. But keeping with the lowest common denominator is a sure way to stall progress. So do you have any suggestion to get out of this impasse? Add another flag to the cover component that indicates if opening/closing state are supported?

**Comment by piitaya** [comment]
Yes it could be a solution. For this kind of feature, it should be propose in the [architecture repository](https://github.com/home-assistant/architecture/discussions).

**Comment by gaaf** [comment]
I've added consideration for such flags to https://github.com/home-assistant/architecture/discussions/979#discussioncomment-7762798

**Comment by Plawasan** [comment]
Just to understand the intent here - I have ESPHome devices controlling my covers (defined as `- platform: time_based` with `stop_action` defined) and I use the stop button to either stop them (when they are not IDLE) or to send them to a pre-defined position when they are IDLE. If the stop button was disabled when the cover is IDLE, I would lose a significant part of the functionality I now have - is that considered or at least configurable to make the stop button always available?

**Comment by wernerhp** [comment]
Can this please be reopened 🙏

**Pull request closed without merging**
