### PR TITLE
Add toggle switch for exposing of new entities to Assist

### PR DESCRIPTION
**Pull request by jpbede**
## Proposed change
Added a toggle switch to disable the exposure of new entities for Assist. As far as I saw core already supports this, but there was no possibility in the frontend so far.

WTH: https://community.home-assistant.io/t/wth-are-all-new-entities-exposed-to-assist-by-default/803889
This seems to be a feature request as well: https://community.home-assistant.io/t/assist-dont-expose-newly-added-entities-automatically-to-it/598434

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
Can we move the toggle row to below the assistants? Also can we make sure the toggle row text aligns with the assistant rows 😄

**Comment by jpbede** [comment]
Should we align the assist rows with the rest?

image

**Comment by bramkragten** [comment]
Yeah, I think that is wise, the row was just copied from the alexa and google one right?

**Comment by jpbede** [comment]
Right

**Review by bramkragten — APPROVED** [review]

**Pull request merged**
