### PR TITLE
Fix 2fa login validation, add autofocus to login

### LINKED ISSUE #22848: Two-factor authentication code input displays an error state on page load
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

image

The two-factor authentication code screen loads into the above state. It shows the error message "Required" despite the form not having been touched by the user.

### Describe the behavior you expected

I'd expect the page to not load into an error state. The error should not display until I attempt to submit the form without a value in the field.

### Steps to reproduce the issue

1. Enable "Authenticator app" under "Multi-factor authentication modules" in Profile -> Security.
2. Log out.
3. Enter username and password, then submit.

### What version of Home Assistant Core has the issue?

2024.11.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.58

### Which operating system are you using to run this browser?

Ubuntu 24.04.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

As a side note, the tab order of this page seems to be incorrect. The field is not auto focused (i.e. after the page loads, typing on my keyboard doesn't result in input in the field), and pressing tab moves focus to the "Submit" button. I _can_ tab my way to the input field, but it takes several presses. In contrast, the tab order on the username/password page is correct. I took a quick look at the HTML of both pages and didn't find any obvious differences between the two.

Search keywords: totp, otp, mfa, multi-factor authentication, two-factor authentication, two factor authentication, multi factor authentication, login

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- Fix login 2fa code validation
- Add login autofocus for username and 2fa code

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #22848
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — COMMENTED** [review]
Should we add the auto focus logic to `ha-form-string` too?

**Comment by wendevlin** [comment]
> Should we add the auto focus logic to `ha-form-string` too?

Yeah we can, but can be in a seperate PR. Would you have already a use case for it?

**Review by MindFreeze — APPROVED** [review]

**Comment by piitaya** [comment]
@wendevlin Not yet but as it's defined in the `HaFormStringSchema` types, I would expect to have support for it, but it's also ok like that.

**Comment by wendevlin** [comment]
> @wendevlin Not yet but as it's defined in the `HaFormStringSchema` types, I would expect to have support for it, but it's also ok like that.

yes you are right, functionality should be there. I'll add it with another PR :+1:

**Pull request merged**
