### PR TITLE
Support time entities in automation time conditions/triggers selectors

### PR DESCRIPTION
**Pull request by markbergsma**
## Proposed change

Allow the new time entities introduced in 2023.6 to be used in automation 'time' conditions, just like input_datetime helpers and sensors with timestamp device class. Add them to the selectors in the frontend.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
condition: time
after: time.time
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion: https://github.com/home-assistant/core/pull/124575
- Link to documentation pull request: home-assistant/home-assistant.io#33217

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Enhanced time-based automation conditions and triggers to support "time" entities.

- **Improvements**
  - Updated descriptions for time-based inputs to include "time entities" for better clarity.

### CODE REVIEW

**Review by silamon — DISMISSED** [review]

**Comment by bramkragten** [comment]
There is a merge conflict, can you please resolve this?

**Review by silamon — APPROVED** [review]

**Comment by edenhaus** [comment]
Core PR is merged, so this one can be merged too

**Comment by wawyed** [comment]
I don't think this solves the problem. I'm still getting validation errors when trying to save

image

**Comment by silamon** [comment]
The better way would be to open an issue. ( I'm opening a PR though and rechecking. )

**Pull request merged**
