### PR TITLE
Improve duration formatting

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

- Merge `format_duration.ts` and `duration.ts` files
- Use duration formatting in entity card to be consistent with other cards
- memoize formatDurationLong
- Fix media_duration formatting (bug introduced with https://github.com/home-assistant/frontend/pull/23017)

Entity card example 

CleanShot 2024-11-27 at 14 50 37

Partial fix for https://github.com/home-assistant/frontend/issues/21346 (graph tooltip is not part of this PR as it requires more work)
Partial fix for https://github.com/home-assistant/frontend/issues/20533 (time default formatting is not part of this PR)

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by ntompson** [comment]
Handling of durations seems to have gone backwards since this update. For example:

Screenshot 2024-12-15 at 8 41 34 PM
Screenshot 2024-12-15 at 8 41 47 PM
Screenshot 2024-12-15 at 8 41 55 PM

I don't have pre-upgrade screenshots, but I'm pretty sure these were formatted more reasonably (hours, minutes and so on).

**Comment by piitaya** [comment]
You can choose the unit using the entity settings. What integration are you using?

CleanShot 2024-12-15 at 11 13 37@2x

CleanShot 2024-12-15 at 11 13 42@2x

**Comment by ntompson** [comment]
Ok great! I didn’t realise that would work. These examples come from ESPHome projects I’ve built myself; they are configured as durations in seconds in ESPHome config. But your method works nicely, so thanks

**Comment by craibo** [comment]
Good day @piitaya, @bramkragten 

After further discussion on https://github.com/home-assistant/frontend/issues/23338 would it be possible to by default use the previous functionality that automatically formatted the value in a human readable way. 
Then the users can decide to use your unit of measure enhancement to override this and force the unit of measure to be used for display?

Also the unit of measure selection field is not showing for me to select on the latest version.

Thank you

**Comment by jouster1974** [comment]
I'm seeing some issues with the new formatting in an integration that previously worked fine with activity lengths being shown in hours, minutes and seconds..whereas now it just shows in seconds.

Please see my further info from my previously logged bug below

Since 2024.12, the time duration seems to have changed to only seconds...and it no longer appears to be possible to change this after a core change, so its no longer possible to show duration in hours, minutes and seconds

395815419-603270d8-1100-4c00-9cb6-a9674316b36d

395815558-c66a6a25-37fb-47a6-80f3-b7d7ebe69f00

For clarity, no further core updates have reverted this issue and from this thread it appears this has been done by design

**Comment by craibo** [comment]
@piitaya, @karwosts  Any update on reverting this change?

**Comment by ntompson** [comment]
> The old format was hh:mm:ss and didn't use the unit of measurement.
> 
> With the new update, the unit of measurement is taken into account. You can choose the unit using the entity settings. What integration are you using? May be it needs a update to provide the right unit by default.

The more I work with this, the more it feels like a backwards step. My main concern is a mixing of data layer and presentation layer, which leads to unexpected outcomes. 

Sensors from ESP devices that were previously reporting seconds I changed to hours using the entity settings as suggested. It sort of fixes the presentation problem, but what I didn't expect was that the underlying unit stored in the entity also changed from seconds to hours. This broke a bunch of automations I had, which were built assuming the entity unit was seconds.

This feels like a fundamentally wrong approach: presentation layer and data layer logic should be kept separate for all the usual reasons. I'd really like to see this change reverted. Not only is it better practice, the old behaviour was also more dynamic, automatically choosing the most appropriate units for the current state (seconds if the amount was low, hours if it was high and so on).

**Comment by piitaya** [comment]
We had many feedbacks and issues open from users that didn't understood that the unit of measurement doesn't affect the display duration. The change fixes that issue. 

The logic is now the same as every unit of measurement (temperature, power, etc...) so the display value will be the one you use for automation for example.

We can consider a `duration_format` options for cards to improve flexibility. We already have `time_format` option for example.

**Comment by craibo** [comment]
Hi @piitaya 

Thank you for responding.

This is **not** true and a very **bad** assumption to make.
> To fix the Strava integration behavior, the suggested unit of measurement can be set to hour (it will display hours and minutes in the UI : 1h 30min). I'm sure people don't need the seconds and days when doing a workout.

I'm a swimmer and the seconds, even milliseconds in time trials, are important. 
I also have a friend who does ultra adventure racing, these events run for a couple days at a time. The full duration time is important (eg. 2 days 21:30:42)

I'm 100% sure this is going to affect other integrations and templates.

> We can consider a duration_format options for cards to improve flexibility.
How can I help to get this added please? If you will not rollback this change, this would be our only option?

I also have to re-iterate on the issue @ntompson raised on the FE and BE mixing of configurations. 
I tried to use this feature to set my energy templates that are tracked in kWh to display in MWh for a yearly template view. 
This actually updated the entity `unit_of_measurement` value and all my sensors then displayed in MWh. When I tried to revert this it broke the values for all the entities and the kWh values were then x1000 out. 
To resolve this I had to create new sensors with different unique names

**Comment by elupus** [comment]
Just a tiny comment, not related to it's be or not to be. The "narrow" format does not really match other entity formatting. We have space between number and unit for most other units, while the narrow format skips that space. Looks inconsistent.

**Comment by unclehack** [comment]
https://github.com/home-assistant/frontend/issues/23338 tracks this issue. https://github.com/home-assistant/frontend/issues/21346 is the original issue for the inconsistent duration formatting.

**Pull request merged**
