### PR TITLE
Remove Zopfli compression

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Uncompressed files are still served so older devices (that don't support brotli) may load slower but should still work

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by piitaya — COMMENTED** [review]
How does it reduce the build time?

**Review by piitaya — APPROVED** [review]

**Comment by steverep** [comment]
Why is this necessary?  I feel like I missed something huge here. 😕

**Comment by MindFreeze** [comment]
Optimizing the build process. Half the build time was taken by this compression and most clients don't use it.

**Comment by steverep** [comment]
> Optimizing the build process. Half the build time was taken by this compression and most clients don't use it.

This change didn't optimize anything.  It just removes compression for everything except the modern build JS, including translations and everything outside the `frontend_latest` directory.  The build time is so much better because it's now doing a small fraction of the original work.  It should be reverted via #23233.

I'm assuming the intention here was to replace Zopfli with Brotli (or at least that's what the reviewers thought it did)?  If so, I think that's a fair trade to consider at this point.  See #23234.

Last but not least, I think it's worth making the point that The legacy build does not exist for **most** clients; it exists for the fringe 10%.  And it's also likely to overlap with the slowest connections.  There's no way we should drastically slow down their load times just to save a few minutes of build time that even most developers never witness.

**Comment by MindFreeze** [comment]
Older devices are not likely to have a slower connection except the 0.001% that are used on a mobile network. Wifi and Ethernet speeds have not been slow for many years. CPU is the limiting factor for old devices.

**Comment by steverep** [comment]
Okay, I don't buy that statistic at all, but even if I did, WiFi and wired connections can be slowed down by congestion, interference, or a poor signal as well.  Bottom line though, fast or slow connection, you'd be hard pressed to find a browser or web developer agreeing that static compression is a waste of time.

**Pull request merged**
