### PR TITLE
Correct overwriting integration labelling on integrations page

### LINKED ISSUE #22776: Show replacing integration on integration entry page.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I really like to see that custom integration that overwrite core integration are highlighted as such on the devices and services page!
IMG_ABCF56BE713D-1

### Describe the behavior you expected

I think it would be great to see the same behavior on the integration entry page as well.
IMG_ABCF56BE713D-2

### Steps to reproduce the issue

1. overwrite a core integration
2. visit the integration entry page
3.
...

### What version of Home Assistant Core has the issue?

2024-11-1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by CFenner**
## Proposed change

This hopefully fixes #22776

Addition to #22295

https://github.com/search?q=repo%3Ahome-assistant%2Ffrontend+ui.panel.config.integrations.config_entry.custom_integration&type=code

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #22776
- This PR is related to issue or discussion: #22295
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by CFenner** [comment]
Unfortunately I have no experience with frontend development or testing. I hope this fixed my issue. Maybe someone can assist with testing.

**Review by MindFreeze — APPROVED** [review]
Thanks @CFenner ! I updated the icon as well

**Comment by CFenner** [comment]
Thanks! 

Did you have a look at https://github.com/MindFreeze/frontend/blob/9adfd802956411a57de87dd6b408473a37468170/src/panels/config/integrations/ha-integration-list-item.ts#L75, does that icon need an update as well?

**Comment by MindFreeze** [comment]
I think it was a design decision not to color the icons there so only the tooltip is different

**Pull request merged**
