### PR TITLE
Move date-range-picker to Top for Logbook and History

### PR DESCRIPTION
**Pull request by LiBe-net**
## Proposed change

This is an missing Style-Improvement for https://github.com/home-assistant/frontend/commit/bed470f79d3b42a2094763eff9a50d583658bcce
@wendevlin:  referring your discussion: https://github.com/home-assistant/frontend/pull/22802#discussion_r1846019700 

Displays Prev. and Next buttons also on mobiles.
Similar to the Energy Dashboard, selecting the date in the header area offers added value, especially on mobile devices.
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by boern99** [comment]
> @boern99 can you add a mobile screenshot too please?

image

**Comment by boern99** [comment]
> In your mobile screenshot I miss the button to select a date?

can be selected by clicking on the date

**Comment by boern99** [comment]
should i use a shorter Date Format? But when i leave the time Information: it would need more space than in Energy Dashboard: 2 Lines for start and end date as in this PR? Leave the Dateselector until there is no space left? Would it be better to hide the Date and leave the Dateselector? If you like to change the code fell free to do so ..

**Comment by wendevlin** [comment]
It's a good idea, but we have to discuss this with the UX team. 
I don't like that the time is seperated from the target picker, moreover you don't see that it is about from - to timerange. 

I am pretty sure we can get an awesome design to improve this selector, it is possible that it can take some time.

**Comment by marcinbauer85** [comment]
@boern99 We've prepared a design that should solve some of the UI/UX problems. 
https://www.figma.com/design/bTQGfCdVnqUYSi7aIJTWkX/HA-20?node-id=2-110&node-type=section&t=QhqWFLDwHzAMsVa3-11

**Comment by boern99** [comment]
> @boern99 We've prepared a design that should solve some of the UI/UX problems. https://www.figma.com/design/bTQGfCdVnqUYSi7aIJTWkX/HA-20?node-id=2-110&node-type=section&t=QhqWFLDwHzAMsVa3-11

Yes this would be better than now but in my opinion not as good as my last version in this pull request. Why has the Energy-Dashboard its Date-Selector in the Header and Loogbook and History should not? This does not look really consistent for me. The header would also have the advantage that it sticks at the top what specially for mobiles would have an advantage.

**Comment by wendevlin** [comment]
The difference to energy dashboards are:
- it is just a day picker
- there are no other inputs

We would like to have all inputs together time range + target picker, that won't be possible in the top bar.

**Comment by boern99** [comment]
> The difference to energy dashboards are:
> 
> * it is just a day picker
> * there are no other inputs
> 
> We would like to have all inputs together time range + target picker, that won't be possible in the top bar.

and what about the "Remove all selections" button? 
image

**Comment by wendevlin** [comment]
😄 good catch. Yeah I would say it is not right placed. 

I understand that you invested time in implementing your solution and thats awesome thank you!

We discussed it and ask for design help from @marcinbauer85. We know that not all parts are consistent and that there are multiple oppinions on how to design panels. We have one more designer and try our best to work on a consistent design everywhere. 

If you don't have enough time to change it to Marcins version, I can try to implement it next week.

**Comment by boern99** [comment]
Tried it and made a draft, but have not uploaded it now as i made some other changes and i am not sure if i should upload it to this pull request, and for the new features, if i should split them into seperate Pull-Requests. 
For the suggested Layout-Change: I am struggling a bit as the ha-textfield uses an input-element. 
image
If we need to have 2 Lines for mobiles: ha-textfield and its input-element is then not suitable. 
I am also testing 2 new functions for zoom-in and zoom-out: We should take into account that we probably need more space for them if they should find its way into a future release?
image
And another change would be an improved logic for recognizing whole month, so that the Previous and Next-Buttons can replace 
"Next Month" and "Next Year". Removing the Previous-Buttons would fit better on mobile-Devices, as now the space on mobiles for the datepicker is borderline.

**Comment by marcinbauer85** [comment]
@boern99 the energy dashboard has a old design implemented, which doesn't account for corner cases like for history and logbook. The top bar is overcrowded especially on mobile, and based even on old MD2 design principles it shouldn't be used for picking dates and filtering (top bars are mostly for navigation and general view options), hence the UI proposed in the design is in the content area, which will lay a foundation for future UX improvements to this and other views.

@wendevlin might help with the input situation.

As for zoom in/out, these are controls that are related to the graph itself, so having them near the date picker might be confusing. Also graphs could benefit of pinch/pan/zoom gestures on mobile, rather than specific buttons.
I know @MindFreeze discussed a possible solution for making graphs more accessible, maybe you could chime in?

**Comment by MindFreeze** [comment]
UX is still subject to change but I am working on zoom for graphs https://github.com/home-assistant/frontend/pull/23183

**Comment by wendevlin** [comment]
@boern99 there is `ha-textarea` maybe you can use this on mobile for multiline?

**Pull request closed without merging**
