### PR TITLE
Fix media browser

### LINKED ISSUE #22755: Home Assistant media browser is broken with >=2024.11
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

after my HA got updated to 2024.11 and 2024.11.1, frigate clips inside media browser does not play videos at all.

### Describe the behavior you expected

frigate clips can play.

### Steps to reproduce the issue

1. update HA to 2024.11 or later.
2. navigate to media browser -> frigate -> clips.
3. open a clip by clicking it.
4. clip never plays.

### What version of Home Assistant Core has the issue?

2024.11.1

### What was the last working version of Home Assistant Core?

2024.10.4

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

ubuntu 24.04.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ivanjx**
## Proposed change

Reintroduce the `url` property for `ha-hls-player` component. Required to play clips that does not have `entityid`.

~Note: currently i cant test it with my existing HA instance (docker compose). Anyone who is willing to test or provide any info on how to do so may chime in.~

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #22755
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]
Thanks!

**Comment by PablaV** [comment]
Will this fix be in a coming 2024.11.4 update or waiting for 2024.12?

**Comment by anton4** [comment]
> Will this fix be in a coming 2024.11.4 update or waiting for 2024.12?

hope it will be 2024.12

**Comment by joos81** [comment]
It looks like it will be in 2024.12
[2024.12.0b2](https://github.com/home-assistant/core/releases/tag/2024.12.0b2) pre-release updates frontend to [20241127.1](https://github.com/home-assistant/frontend/releases/tag/20241127.1)
An this fix is in [20241127.0](https://github.com/home-assistant/frontend/releases/tag/20241127.0)

**Comment by aanban** [comment]
I just did the 2024.12.1 HA core update, the bug fix is included and the frigate clips work again. Great!

**Pull request merged**
