### PR TITLE
Enable chart animations

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

The only reason I see to disable them is that the previous charts didn't have animations. Tested locally and they seem to work fine and make charts nicer.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Might have some performance impact, but we will see 👍

**Comment by karwosts** [comment]
I'm noticing some pretty janky charts today, guessing it's probably this, not sure if you want to pull it:

animate-chart

In person it's actually much more glitchy than captured in the screen record, but I guess that is at lower FPS.

**Comment by MindFreeze** [comment]
Seems to be a Firefox specific issue. It's pretty stable on Chromium. I was going to tweak the animations anyway and if it this persists, I'll just disable them on Firefox

**Comment by MindFreeze** [comment]
@karwosts I can't actually reproduce this. I saw a small jump on open and I thought that was it but I have it even with animations off and I can actually see it in Chromuim too.
You can disable animations globally with `animation: false` [here](https://github.com/home-assistant/frontend/blob/ba3d37b550978fbd18b46fdf7749e07155ceec99/src/components/chart/ha-chart-base.ts#L376) to check if this is the cause for you

**Comment by karwosts** [comment]
My screen recording was from chrome.

**Comment by MindFreeze** [comment]
What OS and do you know if you have hardware acceleration? We still haven't been able to reproduce it. Just reduced the animation duration by half btw so that might affect it

**Comment by karwosts** [comment]
The client was from my Win10 PC, it's got a substantial graphics card but I couldn't say if that's used by the chrome browser or not.

**Comment by karwosts** [comment]
I'm noticing it only happens on the more info with the `Attributes` box at the bottom, entities without that are fine.

**Comment by akoivist** [comment]
This might not be the right place to give feedback anymore, but the animation is really bad for the overall usability on my android tablets using Companion app and W11/Firefox. There is flicker also from scrollbars showing a brief moment.
I would suggest a setting to be able to enable/disable the animation.

**Comment by otterDeveloper** [comment]
***Could you please add an option to disable the animation?***
or revert this pr?

While I understand the intent behind adding the animations, they are not beneficial to the UX in this case. It makes viewing the charts ever so slighty slower. Not all users prefer these animations, and I personally find them distracting.

Also this is not only an UX or performance issue, but this also has ***accesibility concerns***, some users may be affected by animations, since  [`prefers-reduced-motion` is a thing](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)

> Such animations can trigger discomfort for those with [vestibular motion disorders](https://www.a11yproject.com/posts/understanding-vestibular-disorders/). Animations such as scaling or panning large objects can be vestibular motion triggers.

Some guidelines from [this random article](https://www.nngroup.com/articles/animation-purpose-ux/)
>Animation shouldn’t be an afterthought
> Animation must serve a purpose
Gratuitous animation will just take your user’s precious time and after the first initial delight the user will get tired of it, that’s why animation needs to be functional.

**Comment by MindFreeze** [comment]
Just added a [PR to follow accessibility settings](https://github.com/home-assistant/frontend/pull/23777)
An option in HA may still be a good idea but it requires some time while this is a quick win.

**Pull request merged**
