### PR TITLE
Do not always hide CONTINUOUS_DOMAINS in More-Info

### PR DESCRIPTION
**Pull request by LiBe-net**
## Proposed change

I am struggling using Template Sensors having the Domain: sensor and contain for example a Text output. if i click on it the More-Info-Dialog only Shows the History not the Logbook. The color bar chart is very hard to read, so the Loogbook could give an much better overview on status-changes

## Type of change

- [ ] Dependency upgrade
- [ x ] maybe a Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ x ] The code change is tested and works locally.
- [ x ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
We have similar code in data/history.ts (see `isNumeric`) which might be a better change to make, which would only show logbooks when the sensor being shown is not a numeric state or not a numeric device class. 

That might keep a little closer to the original intention. I don't think we want to add logbooks for truly numeric sensors, as that could be messy.

**Comment by karwosts** [comment]
Related #18847

**Comment by frenck** [comment]
There is also a merge conflict @boern99 🙈 

../Frenck

**Comment by boern99** [comment]
updated in @https://github.com/home-assistant/frontend/pull/22762

**Pull request closed without merging**
