### PR TITLE
Fix back button tooltip in Entity history dialog

### PR DESCRIPTION
**Pull request by NoRi2909**
The back button in an entity's History view brings the user back to the 'More info' dialog:

Back to (More) info

The tooltip needs to reflect that by using "Back to More info" for a consistent naming of that dialog.

Example for reference:

https://github.com/home-assistant/frontend/blob/999969b78d5d6d1d9450fb76ca59b1f70d30833c/src/translations/en.json#L6386

## Proposed change

Replace "Back to info" with "Back to More info".

As "More info" is the name of the dialog in HA the first letter is capitalized.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by MindFreeze — COMMENTED** [review]
Technically, History is also part of the "More info" dialog so you are not going back to the dialog but only back to the initial part of it. "info" doesn't mean anything either. I guess the initial view contains the current state. Idk
@googanhiem

**Comment by NoRi2909** [comment]
@MindFreeze The intial dialog "More info" is something like this:

Screenshot 2024-11-24 16 07 26

From there you can go to either History or Settings using the two buttons in the upper right where you will both have the back button with the current "Back to info" tooltip.

**Comment by piitaya** [comment]
More info is the dialog and it's divided in multiple part : info (mainly control except for sensor), history and settings.

**Comment by NoRi2909** [comment]
@piitaya Well, I'm not happy with the current wording. When I started to look over the German translations regarding that dialog we had probably five different variants for the five occurrences.

Like "Mehr Info", "Mehr Infos", "Mehr Informationen", "Weitere Informationen",  "Weitere Infos" …

That's because "Info" alone does not work in German. It's usually only the second part of a compound word. But "More" does not work in building a compound as it's an adjective …

Then I close that PR for now and we'll figure out some solution later.

**Pull request closed without merging**
