### PR TITLE
Don't display nonexistent thermostat current temperature

### PR DESCRIPTION
**Pull request by nattgris**
## Proposed change

Since #7763, the thermostat card has been showing the current temperature as zero, even if the climate entity doesn't provide a current temperature reading. Before that, the current temperature showed as blank (although this was probably due to an oversight because the formatting was a bit weird).

If the climate entity doesn't provide a current_temperature attribute, reuse the space taken up by the meaningless zero, by showing the target temperature in its place.

Before #7763:
previously_scalar_without_current

Currently:
now_scalar_without_current

Proposed change:
suggested_scalar_without_current

Although if the set-point is a range, it doesn't really fit, so in that case show the average of the min/max values (kind of the expected target temperature), while showing the exact range below as before.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: thermostat
entity: climate.hvac
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
I think it might be quite confusing if at the same location we can display two completely different values. Could be easily confused when glancing at multiple thermostats. Perhaps something like this is clearer?

grafik

Also I think having the unit always displayed for the target temperature makes sense. Prevents any confusion what this value might be.

Regardless of which version we end up going with, please also add an example to the gallery coding (gallery/src/demos/demo-hui-alarm-panel-card.ts).

**Comment by bramkragten** [comment]
I agree that we should not move the current value up. I think we can remove the value and the UOM when there is no value?

**Comment by spacegaier** [comment]
> 
> 
> I agree that we should not move the current value up. I think we can remove the value and the UOM when there is no value?

The benefit of my proposal is that the user doesn't think that something is completely wrong (aka has not been rendered) since the card clearly shows that the value is None ("/"). Plus it prevents this weird big empty void that we would otherwise end up with 😄.

**Comment by nattgris** [comment]
TBH the / in the display looks weird, I'd prefer it just empty if you don't like the idea of moving the values around. Which could be somewhat confusing, I agree.

But really, the card is a *thermostat* card, it's main function is to set the *target* temperature, so I think the set-point should be the prominent feature of the card, with the current temperature (if at all available) shown in smaller font below. Take a look at real world traditional thermostats (such as for floor heating etc), if they show a temperature, I think it's most common that it is the desired temperature.

**Comment by bramkragten** [comment]
I think there has been some discussion about this in the past, but I don't think we can make such a change at this moment, as it will cause a lot of confusion.

**Comment by T-bond** [comment]
I think some changes still needed, so please stale bot, remove yourself! :)

**Pull request closed without merging**
