### PR TITLE
Reduce margin between badges and cards

### LINKED ISSUE #22145: Too much space between Badges and Headings
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

It's debatable if this is a bug or not, but when you have badges on your dashboard in combination with headings, the space between the badges and headings is a bit too high for me. It would be nice if this space could be somewhat smaller.
It's about the space which I marked with the red rectangle:

image

### Describe the behavior you expected

Smaller space between badges and headings

### Steps to reproduce the issue

1. Create a dashboard with badges
2. Create sections
3. Create a heading in the sections

### What version of Home Assistant Core has the issue?

2024.10.0b3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.60 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Reduce margin between badges and cards (8px to be consistent with cards and sections).

This PR also set the max-width of badges using the max number of columns in section to have badges container and cards containers aligned.

CleanShot 2024-10-21 at 15 40 00

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/22145
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by marcinbauer85** [comment]
@piitaya Where did this change originated from?

**Comment by piitaya** [comment]
In the Figma design, the space between sections and between cards is the same as the space between cards and badges.
Also in this design,  the header (badges) is aligned with the columns.

CleanShot 2024-10-21 at 15 49 47@2x

**Review by MindFreeze — APPROVED** [review]

**Comment by smarthomejunkie** [comment]
Just updated to 2024.10.4, but the margin between the bags and header is still too big imho. 
IMG_0659

**Comment by piitaya** [comment]
@smarthomejunkie This change will be available in the November release. The last release was only a patch so it doesn't include this change.

**Comment by smarthomejunkie** [comment]
Ah, thank you 🙏🏻

**Comment by Jenik5** [comment]
I have 2025.1 and the space under the badges is still way too big.
image
IMHO it would be very nice to have an option to adjust all spaces between elements.
It is not so many settings:
1) Space under badges
2) Space between sections vertically
3) Space between sections horizontally
4) Space inside sections vertically
5) Space inside sections horizontally
_(4 and 5 could actually be in the section setting.)__

**Pull request merged**
